### ISSUE TITLE
The gear icon doesn't work anymore 

### ISSUE THREAD

**Issue by igloows** [personalizedrefrigerator/joplin-plugin-extra-viewer-settings#1]
When I try to change the settings by clicking on the gear icon in Android it doesn't do anything. What should I do?

![Screenshot_20240920-150141~2](https://github.com/user-attachments/assets/38d82195-fa38-4948-b99f-128d8072d071)

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!

Information that could be helpful:
- Is this the case for all notes, or just the "1. Welcome to Joplin" note?
- Does disabling pagination in Joplin's settings > Extra viewer settings > paginate help?
- What version of the plugin are you using?
   - This can be found under the "Plugins" tab in Joplin's settings.

**Comment by igloows** [comment]
Thank you for your help

This is happening for all my notes.

With pagination disabled is still the same.

Plugin version: 0.3.0
Joplin Version: 3.0.8

**Comment by personalizedrefrigerator** [comment]
Here are two possible causes of the issue:
- Android WebView version: The settings button may be broken with a particular version of Android's WebView.
- Other plugins: The settings button might conflict with another plugin.

Does disabling all other plugins help? What WebView version is listed in Joplin settings > More information?

**Comment by igloows** [comment]
Joplin 3.0.8 (prod, android)

Extra Markdown viewer settings: 0.3.0

Android API level: 31
WebView version: 105.0.5195.136
WebView package: com.google.android.webview
Hermes enabled: 1

There is no other plugin installed

**Comment by personalizedrefrigerator** [comment]
This seems to be related to the WebView version &mdash; this plugin makes use of nested CSS, which is only supported in [Android WebView >= 128](https://caniuse.com/css-nesting). I'm now refactoring the plugin to avoid using nested CSS.

**Comment by personalizedrefrigerator** [comment]
This should be fixed in v0.4.0. It may take 30-60 minutes for the update to be available.

**Comment by igloows** [comment]
Thank you! It works!
